# fly.toml app configuration file generated for apollosolutions--financial-supergraph on 2023-05-26T11:01:30-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apollosolutions--financial-supergraph"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "paketobuildpacks/builder:full"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[experimental]
  auto_rollback = true

[env]
  NODE_ENV = "fly"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
