name: merge-to-main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-monolith:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly
        run: flyctl deploy --remote-only

  subgraph-accounts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: apollosolutions/rover-actions/install-rover-cli@v1

      - name: Publish README
        run: rover readme publish apollo-financial-supergraph@prod --file README.md

      - name: Publish accounts schema
        working-directory: ./subgraphs/accounts
        run: |
          rover subgraph publish apollo-financial-supergraph@prod \
            --name accounts \
            --schema schema.graphql

      - name: Publish credit schema
        working-directory: ./subgraphs/credit
        run: |
          rover subgraph publish apollo-financial-supergraph@prod \
            --name credit \
            --schema schema.graphql

      - name: Publish risk schema
        working-directory: ./subgraphs/risk
        run: |
          rover subgraph publish apollo-financial-supergraph@prod \
            --name risk \
            --schema schema.graphql

      - name: Publish transactions schema
        working-directory: ./subgraphs/transactions
        run: |
          rover subgraph publish apollo-financial-supergraph@prod \
            --name transactions \
            --schema schema.graphql

      - name: Publish users schema
        working-directory: ./subgraphs/users
        run: |
          rover subgraph publish apollo-financial-supergraph@prod \
            --name users \
            --schema schema.graphql
